### ISSUE TITLE
no implicit conversion of nil into string typeerror

### ISSUE THREAD

**Issue by duenni** [christopher-b/flac-to-itunes#2]
Hi!

I used your workflow to generate an Automator Service for converting FLAC to MP3. It worked until Yosemite came out. I have a "Run Shell Script"-Action with the following:

```
# Set the following to the folder containing metaflac, flac, flac2mp3 and lame binaries. 
# Install flac from homebrew
flac_bin = "/usr/local/bin"

# Change working folder so the files will be saved in the same folder
export_folder = File.dirname(ARGV.first)
Dir.chdir(export_folder)

# Set path
path = ENV['PATH']
path = "#{path}:#{flac_bin}"
ENV['PATH'] = path
ARGV.each do |file|
    next if File.extname(file) != '.flac'
    `flac2mp3 "#{file}"`
    puts export_folder + "/" + File.basename(file,'.*')+".mp3"
end
```

And now I get the following error
`dirname: no implicit conversion of nil into String (TypeError)` 
on line
 `export_folder = File.dirname(ARGV.first)`
when running this with Automator. Any idea? I am in no way a ruby expert.
Thanks in advance!

**Comment by tim-tation** [comment]
Thanks alot, but how is it now possible to adjust the quality?
# Set quality between "#{file}“ and `: V2, V1, V0, 320
doesn't work anymore.

**Comment by christopher-b** [comment]
```ruby 
system({"PATH"=>ENV['PATH']}, "flac2mp3", file, "V0")
```
should do it.

**Comment by tim-tation** [comment]
Wow thanks, that was fast!
320 ist still the best, right?

**Comment by christopher-b** [comment]
[This page](http://wiki.hydrogenaud.io/index.php?title=LAME#Recommended_encoder_settings) explains the differences. 320 will give you a constant 320kbps, while V0 will output a variable bitrate MP3 at around 245kbps. 320 will also increase the file size. 

According to the link above, there is rarely a perceptible difference between V0, V1 and V2, and "no one has produced ABX test results demonstrating that perceived quality [of 320 CBR] is ever better than the highest VBR profiles described above".

So, if you don't mind the larger files, go with 320. Otherwise, stick with the default: V0.
